### ISSUE TITLE
Change license terms

### ISSUE THREAD

**Issue by AntMaster7** [MikeMcShaffry/gamecode4#20]
Would be nice if the license could be changed to a more permissive license. The LGPL license still comes with many conditions.

**Comment by MikeMcShaffry** [comment]
I understand - but since the license is mentioned in the printed book, I can't really change it. But, if you personally needed a more permissive license, I'm sure I can help you. Reach out to me personally at mrmike at mcshaffry dot com!

**Comment by AntMaster7** [comment]
Thank you so much for your reply. Tbh, I initially didn't even expect a reply at all because the last push to this repository was years ago.

**Comment by MikeMcShaffry** [comment]
Well email still seems to work most days! Anyway - I wouldn't use any of
the code in a commercial project anyway for two reasons. First, it is more
geared to teach how game engines work, and second it is very old. So, the
LGPL ended up being a pretty good license after all.

Take care,
Mike
